# Generated by cucumber-sinatra. (2014-09-14 13:20:12 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'cookie.rb')

require 'rspec'
require 'capybara'
require 'capybara/cucumber'

Capybara.app = CookieGame

class CookieGameWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  CookieGameWorld.new
end